export default {
    CHANGE_CAMPAIGN: 'CHANGE_CAMPAIGN',
    CHANGE_SCENARIO: 'CHANGE_SCENARIO',
    CHANGE_DIFFICULTY: 'CHANGE_DIFFICULTY',
    CHANGE_TOKEN_AMOUNT: 'CHANGE_TOKEN_AMOUNT',
    PULL_TOKEN: 'PULL_TOKEN',
    PUT_TOKEN_BACK: 'PUT_TOKEN_BACK'
}
